### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by xbadal** [octomato/preload_page_view#16] opened 2020-09-25 21:01 UTC
error keeps on coming for no reason. 

Null check operator used on a null value

please let me know what to do?

**Comment by Quving** [comment] 2020-10-16 14:17
I am also running into this problem! :)

**Comment by xbadal** [comment] 2020-10-17 04:44
Just try to switch from flutter stable to flutter beta. it worked for me. @Quving

**Comment by Quving** [comment] 2020-10-19 11:33
Ah thanks a lot. I also found out using flutter stable tags such as version 1.22.2 works also fine.

**Comment by savs90** [comment] 2020-10-30 14:38
Duplicate of  #18

**Comment by xbadal** [comment] 2020-10-30 18:45
> Duplicate of #18

please check date before marking it duplicate. #18 is Duplicate of #16

**Comment by crtl** [comment] 2020-11-06 09:11
Having the same issue. Seems to be related to [https://github.com/flutter/flutter/issues/66250](https://github.com/flutter/flutter/issues/66250)

**Comment by crtl** [comment] 2020-11-06 10:28
savs90 provided a fix in https://github.com/octomato/preload_page_view/issues/18.
Ive implemented in a new fork which is available with:
```
preload_page_view:
    git:
      url: "https://github.com/crtl/preload_page_view.git"
      ref: "fix-null-check-operators"
```

**Comment by octomato** [comment] 2021-01-07 14:33
Close this ticket because it duplicate with https://github.com/octomato/preload_page_view/issues/18

**Closed by octomato** 2021-01-07 14:33 UTC
